include = ["Cargo.toml", "crates/**/*.toml"]

[formatting]
align_comments = true
align_entries = true
allowed_blank_lines = 2
# Collapse into one line if array is under column width
array_auto_collapse = true
# Expand into multiple lines if array is over column width
array_auto_expand = true
array_trailing_comma = true
compact_entries = false
reorder_arrays = true
reorder_keys = false

# Override to alphabetically sort dependencies in Cargo.toml files
[[rule]]
include = ["Cargo.toml", "crates/**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies"]

[rule.formatting]
reorder_keys = true

# Override to alphabetically sort all keys in config toml files
[[rule]]
include = ["crates/**/config/*.toml"]

[rule.formatting]
reorder_keys = true
